# Generated by Django 4.2.9 on 2026-06-10 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prevalence", "0013_remove_clinicaldiagnosis"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClinicalDX",
        ),
    ]
