# Generated by Django 4.2.9 on 2025-05-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prevalence", "0009_alter_disease_do_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="SNOMEDCT_US_2024_03_01",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
