# Generated by Django 4.2.9 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prevalence", "0010_disease_snomedct_us_2024_03_01"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("clinical_dx_code", models.CharField(max_length=200)),
            ],
        ),
    ]
